server:
  port: 9001
spring:
  application:
    name: YIGOU-PRODUCT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///yigou-product?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
#别名配置
mybatis-plus:   
  type-aliases-package: cn.itsource.yigou.domain,cn.itsource.yigou.query