#服务提供者
server:
  port: 8001
spring:
  application:
    name: YIGOU-PLATspring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///yigou-plat?useSSL=false
    username: root
    password: root
